version: '3.4'
services:
  swoole:
    container_name: "swoole"
    image: "phpswoole/php:${PHP_VERSION}"
    volumes:
      - "${TRAVIS_BUILD_DIR}:/swoole-src:rw"
    working_dir: /swoole-src
    ulimits:
      core: -1
    privileged: true
    depends_on:
      - mysql
      - redis
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SWOOLE_BRANCH: "${TRAVIS_BRANCH}"
    command: tail -f /etc/group
  mysql:
    container_name: "mysql"
    image: "twosee/swoole:mysql5"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./data/run/mysqld:/var/run/mysqld:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: swoole
      MYSQL_PASSWORD: swoole
  redis:
    container_name: "redis"
    image: "twosee/swoole:redis"
    volumes:
      - ./data/redis:/var/lib/redis:rw
      - ./data/run/redis:/var/run/redis:rw
    sysctls:
        net.core.somaxconn: 65535
  httpbin:
    container_name: "httpbin"
    image: "kennethreitz/httpbin"
  tinyproxy:
    container_name: "tinyproxy"
    image: "vimagick/tinyproxy"
  golang-h2demo:
    container_name: "golang-h2demo"
    image: "phpswoole/golang-h2demo"
  socks5:
    container_name: "socks5"
    image: "xkuma/socks5"
  ftp:
    container_name: "ftp"
    image: "fauria/vsftpd"
    environment:
      FTP_USER: admin
      FTP_PASS: admin

