name: lib-swoole

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: phpize && ./configure --enable-sockets --enable-mysqlnd --enable-http2 --enable-debug-log
    - name: export
      run: export SWOOLE_DIR=`pwd`
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: cd core-tests && cmake . && make
    - name: test
      run: cd - && cd core-tests && bin/core-tests 
