name: lib-swoole

on: [push, pull_request]

env:
  CODECOV_TOKEN: "50513381-198e-43d3-a8b1-e36b95038927" # from: https://codecov.io/gh/swoole/swoole-src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: gtest_install
      run: sudo apt install -y googletest libgtest-dev redis-server &&
           cd /usr/src/googletest/googletest &&
           sudo mkdir build &&
           cd build &&
           sudo cmake .. &&
           sudo make &&
           sudo make install &&
           cd - &&
           sudo rm -rf /usr/src/googletest/googletest/build

    - name: configure
      run: phpize && ./configure --enable-sockets --enable-mysqlnd --enable-http2

    - name: make
      run: cmake . -DCODE_COVERAGE=ON && make VERBOSE=1 && sudo make install

    - name: make test
      run: cd core-tests && ./run.sh

    - name: run coverage
      shell: bash
      run: sudo apt-get install lcov &&
          sudo lcov --directory . --capture --output-file coverage.info &&
          sudo lcov --remove coverage.info "${{runner.workspace}}/swoole-src/include/*" '/usr/*' --output-file coverage.info &&
          sudo lcov --list coverage.info &&
          sudo curl -s https://codecov.io/bash -o codecov.sh &&
          sudo chmod +x codecov.sh && sudo ./codecov.sh -f coverage.info -t ${CODECOV_TOKEN}
