name: Thread Support Tests

on: [push, pull_request]

jobs:
  test-linux:
    if: "!contains(github.event.head_commit.message, '--filter=') || contains(github.event.head_commit.message, '[thread]')"
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1-zts', '8.2-zts', '8.3-zts', '8.4-zts']
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    name: ${{ matrix.php }}-thread-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
        coverage: none
      env:
        phpts: ts
    - name: Show machine information
      run: |
        php -v
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - name: Run tests
      run: |
        export SWOOLE_CI_TYPE=THREAD
        export SWOOLE_BRANCH=${GITHUB_REF##*/}
        export SWOOLE_BUILD_DIR=$(realpath .)
        export PHP_VERSION=${{ matrix.php }}
        ${SWOOLE_BUILD_DIR}/scripts/route.sh
